import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import DataProvider from "@/context/dataContext";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
    >
      <body className="bg-base-200">
        <DataProvider>
          <Navbar></Navbar>
          <section className="px-2">
            {children}
          </section>
          <Footer></Footer>
        </DataProvider>
      </body>
    </html>
  );
}
